### ISSUE TITLE
How do I use getConnectedSSID

### ISSUE THREAD

**Issue by grimace** [arsenal942/Cordova-Network-Manager#10]
﻿

### Prerequisites

Check all boxes if you have done the following:
- [X] Checked that your issue isn't already filed: https://github.com/arsenal942/Cordova-Network-Manager/issues
- [X] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [ ] Bug
- [ ] Enhancement
- [ ] Task
- [X] Question
- [ ] Other

### Description
just looking for documentation...

1. [First Step]
I'm using this to successfully add and connect to networks on android and IOS, but don't know how to add this particular function (**getConnectedSSID**) to test if I'm already connected to the SSID that I want.

I can't find any documentation on how to use this function. Any help would be appreciated.

**Comment by gregor-srdic** [comment]
i believe ***getCurrentSSID*** is the  correct function in javascript

```
cordovaNetworkManager.getCurrentSSID(
    (r) => {
        console.log(r);
     },
     (err) => console.log(err)
)
```

**Comment by arsenal942** [comment]
Hi @grimace 
Sorry for the late response. I was overseas on holidays for the last 4 weeks and took a detox from everything dev related.

As @gregor-srdic said above, that is the correct function to get the current connected SSID. 

The first parameter in the success callback is the currently connected SSID and is a global function for both iOS and Android platforms.

Below is a code example:

```
            cordovaNetworkManager.getCurrentSSID(function (currentSsid) {
                //currentSsid is the connected SSID. Perform some validation to ensure it is not null, not length of 0 and not undefined.
            }, function () {
                //error. Plugin failed or something.
            });
```

It is important to note that Android returns the SSID with an extra set of "" wrapped around it. Usually what I do in the success callback is format the currentSsid and some form of validation to make sure it isn't null

An example of formatting the currentSsid is below:
```
this.formatCurrentSsid = function (currentSsid) {
            if (currentSsid !== undefined && currentSsid !== null) {
                if (cordova.platformId === "ios") {
                    return currentSsid;
                } else {
                    return currentSsid.substring(1, currentSsid.length - 1);
                }   
            } else {
                return false;
            }
        };
```


Let me know if the above was helpful or if you need some further clarification.

**Comment by arsenal942** [comment]
Closed because my OG comment explains how to use the method.
