### ISSUE TITLE
Is it possible to list available networks on iOS

### ISSUE THREAD

**Issue by gregor-srdic** [arsenal942/Cordova-Network-Manager#11]
Check all boxes if you have done the following:
- [X] Checked that your issue isn't already filed: https://github.com/arsenal942/Cordova-Network-Manager/issues
- [X] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [ ] Bug
- [ ] Enhancement
- [ ] Task
- [X] Question
- [ ] Other

### Description

Is it possible to list available networks on iOS? I would like to see the networks around the user device and offer him to connect if any network name matches a specific pattern (for instance starts with 'mydevice').

**Comment by arsenal942** [comment]
Hi @gregor-srdic,
Sorry for the late response. I was overseas on holidays for the last 4 weeks and took a detox from everything dev related.

As far as I am aware, we can't do this, even with the 'enhanced' capabilities brought to us with iOS11. The only functionality we can do with iOS is getCurrentSSID, getCurrentBSSID, connect to a wifi network and disconnect from a wifi network.

The TLDR is that iOS has limited functionality as Apple's WifiManager equivalent is only available as a private API. Any app that used these features would not be allowed on the app store.

That being said, I will have a browse of the interwebs to double check what I said is still valid.

**Comment by captainreptile** [comment]
@gregor-srdic I guess we are looking for the same functionalities:
scan wifi > connect/discconect from wifi
i understand IOS only recently started to allow this, and some permissions are needed from Apple: 
https://developer.apple.com/documentation/networkextension/nehotspothelper

Would be lovely to see a way to implment this helper to this cordova module

**Comment by gregor-srdic** [comment]
Thanks to both of you, I was trying to develop this myself as well and got stuck here :S 
If I am not mistaken, this functionality would require MFI certification from apple, which became free recently for software apps? 
Unfortunatelly I am not much of a iOS developer to clearly understand this.

**Comment by captainreptile** [comment]
@gregor-srdic The MFI developer license costs the verification process by 3rd party (source: https://mfi.apple.com/MFiWeb/getFAQ.action).   This in additional to the Apple developer license.

As i see usage of Wifi is included in the MFI scope... but there could be an easier enrollment if using only the HotspotHelper.  This i cannot confirm yet as i don't have yet the Apple developer license and i don't know whats behind this page: https://developer.apple.com/contact/network-extension


p.s: i am braking my head as well with this and ways to implement in app..

**Comment by arsenal942** [comment]
As I stated above, there is no way due to the Apple API restrictions. All NEHotspotHelper does is lets you connect and disconnect from a specified network (as long as it is available). This plugin already implements that via `iOSConnectNetwork` and `iOSDisconnectNetwork`.

Closed.
