### ISSUE TITLE
Missing ACCESS_COARSE_LOCATION permission

### ISSUE THREAD

**Issue by MumblesNZ** [arsenal942/Cordova-Network-Manager#12]
﻿

### Prerequisites

Check all boxes if you have done the following:
- [y ] Checked that your issue isn't already filed: https://github.com/arsenal942/Cordova-Network-Manager/issues
- [ y] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [ y] Bug
- [ ] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description

getScanResults function doesn't work without androids ACCESS_COARSE_LOCATION permission set in the manifest. I believe this permission is missing in the plugin.xml file. 

        <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

### Steps to Reproduce

Try and request ACCESS_COARSE_LOCATION using "cordova-plugin-android-permissions" v1.0.0. This returns {"hasPermission":false}

Try and run getScanResults on an android device running android version 8.1.0.  This will return an empty array, and the ADB link states "WifiPermissionsUtil: Denied: no location permission".

To solve, add <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" /> to the android manifest. 

### Versions

Android version: 8.1.0
Ionic version: 3.19.1
cordovanetworkmanager version: 2.3.0,

**Comment by arsenal942** [comment]
I will include the missing permission in the next release. ETA: 3-5 business days. 
I'll close the issue once it is live/deployed.

**Comment by arsenal942** [comment]
Also this is most likely a device/platform specific issue. I am still able to perform scans on multiple Android devices without it. That being said, I will still include it because not everyone is the same.

**Comment by MumblesNZ** [comment]
Thanks @arsenal942 much appreciated.

**Comment by arsenal942** [comment]
@MumblesNZ I did notice you have forked the repo. I do accept pull requests so in future keep that in mind and feel free to contribute. :D

**Comment by arsenal942** [comment]
Release v2.4.0 fixed.
