### ISSUE TITLE
xCode simulator fail

### ISSUE THREAD

**Issue by Melcus** [arsenal942/Cordova-Network-Manager#14]
### Issue type
Select all that apply
- [ ] Bug
- [x] Enhancement
- [ ] Task
- [X] Question
- [ ] Other

### Description
*This will not run in the xCode simulator and requires a physical iOS device to be connected to the machine when building. If you don't attach a physical device, the build will fail.*   It seems the problem from wifiwizard is still here .. 

Is there any way we can get past this ? Won't this get blocked in the iOS app store ?

**Comment by arsenal942** [comment]
@Melcus Unfortunately no. You are still able to build your application and upload it to the app store without any problems. An actual human being at Apple downloads and reviews every application prior to approval.

HotspotConfiguration and NetworkExtensions don't work in the iOS simulator. I hope they change this soon.

**Comment by arsenal942** [comment]
As of the latest xCode however, I have been able to at least build the application **without** having to have an iOS based device plugged in. It still doesn't work in the simulator though.
