### ISSUE TITLE
Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N

### ISSUE THREAD

**Issue by coloz** [arsenal942/Cordova-Network-Manager#18]
show the error
> cordovanetworkmanager\cordovaNetworkManager.java:66: Error: The WIFI_SERVICE must be looked up on the Application context or memory will leak on devices < Android N. Try changing cordova.getActivity() to cordova.getActivity().getApplicationContext() [WifiManagerLeak]

hope update the plugin to Arduino N

**Comment by arsenal942** [comment]
Sorry I've been away for a bit. I reviewed and merged your PR.
