### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by arsenal942** [arsenal942/Cordova-Network-Manager#6]
### Issue type
- [x] Task

### Description
There is a task for myself to improve the documentation so that every function is adequately explained. This will include code examples that will give users an in depth insight into how a function operates.

**Comment by MumblesNZ** [comment]
Hey, could you give an example of how we should implement getScanResults? Not sure what options parameter is? Do you need to call startScan first?

**Comment by arsenal942** [comment]
Release v2.4.0 fixed.
