### ISSUE TITLE
getCurrentSSID() returns SSID even when not connected (getCurrentBSSID does not exist)

### ISSUE THREAD

**Issue by tripflex** [arsenal942/Cordova-Network-Manager#7]
Seems that `getCurrentSSID` returns an SSID even when it's not connected to that network, which calls the `getConnectedSSID`

see: https://stackoverflow.com/questions/41366481/android-why-wifimanager-getconnectioninfo-getssid-return-disconnected-ssid
https://developer.android.com/reference/android/net/wifi/WifiInfo.html#getSSID()

Trying to use this to handle the `ssidToDisconnect` 

Reading the docs it seems that `getCurrentBSSID` would work (as it should return null if not connected), but even though that method is available, it does not exist in main java file (which I found is actually related to the WiFiWizard, not your edits)

**Comment by arsenal942** [comment]
Good spot. This goes back to the OG WifiWizard code being a bit trash. 

I'm just going to re-write the entire Android platform side since it makes a lot more sense to do so.

**Comment by arsenal942** [comment]
Working on this now.

**Comment by arsenal942** [comment]
@tripflex 'getConnectedBSSID' now exists and the OG getConnectedSSID has been modified. Check #3deb50f to see the changes.

**Comment by arsenal942** [comment]
Release v2.4.0 fixed.
