### ISSUE TITLE
It does not work in IOS

### ISSUE THREAD

**Issue by obravoInserious** [arsenal942/Cordova-Network-Manager#9]
I am currently using IOS 11.2.2 and Xcode 9.2, when trying to connect to the wifi it does not return an error but it does not connect either.

I tried with the wifi on and with the wifi off

**Comment by arsenal942** [comment]
Hi @obravoInserious,
Sorry for the late response. I was overseas on holidays for the last 4 weeks and took a detox from everything dev related.

You can not run this in the simulator. You have to have an actual iOS device (iPhone, iPad) connected when you build.

You also need to have Network Extensions and Personal VPN capabilities enabled for this to work. 

Let me know how you go after trying the above.

**Comment by arsenal942** [comment]
Closing because it does work on iOS and you just need to implement the changes I said in my OG comment.
